# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=500, verbose_name='密码'),
        ),
    ]
