# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=80)),
                ('rtime', models.DateField(auto_now_add=True)),
                ('rmark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BasicRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnum', models.IntegerField(default=0)),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('province', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('area', models.CharField(default='', max_length=20)),
                ('caddr', models.CharField(max_length=80)),
                ('lxr', models.CharField(max_length=20)),
                ('lxrphone', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=20)),
                ('avaliable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=15)),
                ('e_age', models.IntegerField()),
                ('e_sex', models.BooleanField(default=True)),
                ('e_tel', models.CharField(default='', max_length=15)),
                ('e_ctime', models.DateField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=15)),
                ('good_status', models.BooleanField(default=True)),
                ('origin_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('good_img', models.FileField(default=None, upload_to='.goods/upload/')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('g_sort_num', models.IntegerField(default=1)),
                ('g_disc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('t_sort_num', models.IntegerField(default=1)),
                ('discription', models.CharField(default=None, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('cost_price', models.FloatField(default=0)),
                ('remark', models.CharField(default='', max_length=50)),
                ('in_date', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Good')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='OutRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_num', models.IntegerField(default=0)),
                ('sell_money', models.FloatField(default=0)),
                ('out_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Customer')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Good')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Paytype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=10)),
                ('isActive', models.BooleanField(default=True)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('province', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('area', models.CharField(default='', max_length=20)),
                ('phone_number', models.CharField(default='', max_length=11)),
                ('email', models.CharField(default='', max_length=30)),
                ('business', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('province', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('area', models.CharField(default='', max_length=20)),
                ('s_addr', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=30)),
                ('linkman', models.CharField(max_length=15)),
                ('tel', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=30)),
                ('card', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('paytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Paytype')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Shop'),
        ),
        migrations.AddField(
            model_name='outrecord',
            name='paytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Paytype'),
        ),
        migrations.AddField(
            model_name='outrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Shop'),
        ),
        migrations.AddField(
            model_name='inrecord',
            name='paytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Paytype'),
        ),
        migrations.AddField(
            model_name='inrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Shop'),
        ),
        migrations.AddField(
            model_name='inrecord',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Supplier'),
        ),
        migrations.AddField(
            model_name='good',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Position'),
        ),
        migrations.AddField(
            model_name='city',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Province'),
        ),
        migrations.AddField(
            model_name='basicrecord',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Good'),
        ),
        migrations.AddField(
            model_name='basicrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Shop'),
        ),
        migrations.AddField(
            model_name='basicrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Customer'),
        ),
        migrations.AddField(
            model_name='backrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Employee'),
        ),
        migrations.AddField(
            model_name='backrecord',
            name='outrecord',
            field=models.ManyToManyField(to='index.OutRecord'),
        ),
        migrations.AddField(
            model_name='area',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.City'),
        ),
    ]
