# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Area'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.City'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Province'),
        ),
    ]
