# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181214_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodtype',
            name='shop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.Shop'),
        ),
    ]
