# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_paytype_snum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='paytype',
        ),
    ]
