# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_supplier_paytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='area',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='province',
            field=models.CharField(default='', max_length=20),
        ),
    ]
