# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_backrecord_r_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='isActive',
            new_name='right',
        ),
    ]
