# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20181215_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='s_name',
        ),
    ]
