# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_supplier_s_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicrecord',
            name='in_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicrecord',
            name='out_num',
            field=models.IntegerField(default=0),
        ),
    ]
