# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_basicrecord_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicrecord',
            name='is_del',
            field=models.BooleanField(default=True),
        ),
    ]
