# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_basicrecord_is_del'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backrecord',
            name='outrecord',
        ),
    ]
