# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_remove_backrecord_outrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='backrecord',
            name='good',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='backrecord',
            name='r_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backrecord',
            name='shop',
            field=models.CharField(default='', max_length=30),
        ),
    ]
