# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-16 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_backrecord_outrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backrecord',
            options={'verbose_name': '退库单', 'verbose_name_plural': '退库单'},
        ),
        migrations.AlterModelOptions(
            name='basicrecord',
            options={'verbose_name': '库存清单', 'verbose_name_plural': '库存清单'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '顾客', 'verbose_name_plural': '顾客'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goodtype',
            options={'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterModelOptions(
            name='inrecord',
            options={'verbose_name': '进货单', 'verbose_name_plural': '进货单'},
        ),
        migrations.AlterModelOptions(
            name='outrecord',
            options={'verbose_name': '出库记录', 'verbose_name_plural': '出库记录'},
        ),
        migrations.AlterModelOptions(
            name='paytype',
            options={'verbose_name': '支付', 'verbose_name_plural': '支付'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '职位', 'verbose_name_plural': '职位'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '店铺', 'verbose_name_plural': '店铺'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Customer', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='good',
            field=models.CharField(default='', max_length=30, verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Employee', verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='outrecord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.OutRecord', verbose_name='支出'),
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='r_money',
            field=models.IntegerField(default=0, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='r_num',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='reason',
            field=models.CharField(max_length=80, verbose_name='理由'),
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='rmark',
            field=models.CharField(max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='rtime',
            field=models.DateField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='backrecord',
            name='shop',
            field=models.CharField(default='', max_length=30, verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='cdate',
            field=models.DateTimeField(auto_now=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='gnum',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Good', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='in_num',
            field=models.IntegerField(default=0, verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='income',
            field=models.IntegerField(default=0, verbose_name='收入'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='is_del',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='loss',
            field=models.IntegerField(default=0, verbose_name='损耗'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='out_num',
            field=models.IntegerField(default=0, verbose_name='出价'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Shop', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.CharField(max_length=50, verbose_name='支付'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.CharField(default='', max_length=20, verbose_name='区/县'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avaliable',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.CharField(max_length=50, verbose_name='银行'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='caddr',
            field=models.CharField(max_length=80, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cname',
            field=models.CharField(max_length=50, verbose_name='顾客名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(max_length=20, verbose_name='传真'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lxr',
            field=models.CharField(max_length=20, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lxrphone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(default='', max_length=20, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_ctime',
            field=models.DateField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_name',
            field=models.CharField(max_length=15, verbose_name='员工姓名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_sex',
            field=models.BooleanField(default=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_tel',
            field=models.CharField(default='', max_length=15, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='是否生效'),
        ),
        migrations.AlterField(
            model_name='good',
            name='g_disc',
            field=models.TextField(default='', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='good',
            name='g_sort_num',
            field=models.IntegerField(default=1, verbose_name='销售数量'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_img',
            field=models.FileField(default=None, upload_to='.goods/upload/', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_status',
            field=models.BooleanField(default=True, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_name',
            field=models.CharField(max_length=15, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodType', verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='good',
            name='origin_price',
            field=models.FloatField(verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sell_price',
            field=models.FloatField(verbose_name='销售价格'),
        ),
        migrations.AlterField(
            model_name='good',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='discription',
            field=models.CharField(default=None, max_length=30, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='name',
            field=models.CharField(max_length=15, verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='shop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.Shop', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='t_sort_num',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='cost_price',
            field=models.FloatField(default=0, verbose_name='支出成本'),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Good', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='in_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='num',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Employee', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='paytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Paytype', verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='remark',
            field=models.CharField(default='', max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Shop', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Customer', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Good', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Employee', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='out_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='paytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Paytype', verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='sell_money',
            field=models.FloatField(default=0, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='sell_num',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Shop', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='paytype',
            name='snum',
            field=models.IntegerField(default=1, verbose_name='支付类型'),
        ),
        migrations.AlterField(
            model_name='paytype',
            name='type_name',
            field=models.CharField(max_length=20, verbose_name='支付名称'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='position',
            name='p_name',
            field=models.CharField(default='', max_length=10, verbose_name='职位名称'),
        ),
        migrations.AlterField(
            model_name='position',
            name='right',
            field=models.BooleanField(default=True, verbose_name='是否更改'),
        ),
        migrations.AlterField(
            model_name='position',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Shop', verbose_name='店铺名称'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='area',
            field=models.CharField(default='', max_length=20, verbose_name='区/县'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='老板'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='business',
            field=models.CharField(default='', max_length=100, verbose_name='店铺名称'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.CharField(default='', max_length=30, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活动'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=15, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(default='', max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='province',
            field=models.CharField(default='', max_length=20, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='area',
            field=models.CharField(default='', max_length=20, verbose_name='区/县'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank',
            field=models.CharField(max_length=30, verbose_name='银行'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='card',
            field=models.CharField(max_length=20, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.CharField(max_length=30, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=30, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='linkman',
            field=models.CharField(max_length=15, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='province',
            field=models.CharField(default='', max_length=20, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='s_addr',
            field=models.CharField(max_length=50, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tel',
            field=models.CharField(max_length=30, verbose_name='电话'),
        ),
    ]
