# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-28 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20190118_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
